### ISSUE TITLE
VersionConflict: (letsencrypt 0.1.1 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('letsencrypt>=0.1.2'))

### ISSUE THREAD

**Issue by ChrisRut** [dlapiduz/letsencrypt-s3front#16]
I am getting the following when attempting to run:
```
root@97ff5ba02845:/# letsencrypt --text --agree-tos -a letsencrypt-s3front:auth \
> --letsencrypt-s3front:auth-s3-bucket $S3_BUCKET \
> -i letsencrypt-s3front:installer \
> --letsencrypt-s3front:installer-cf-distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
> -c /etc/letsencrypt/cli.ini
An unexpected error occurred:
VersionConflict: (letsencrypt 0.1.1 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('letsencrypt>=0.1.2'))
Please see the logfile 'letsencrypt.log' for more details.
```

Here is the contents of the *letsencrypt.log*:
```
Traceback (most recent call last):
  File "/usr/local/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1349, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/local/lib/python2.7/dist-packages/letsencrypt/plugins/disco.py", line 168, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/local/lib/python2.7/dist-packages/letsencrypt/plugins/disco.py", line 31, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2379, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2396, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (letsencrypt 0.1.1 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('letsencrypt>=0.1.2'))
```
It looks like this commit is the cause: https://github.com/dlapiduz/letsencrypt-s3front/commit/3d75b4eac41efc3a5d7d9ea7f8a32b87b6abf74b

Letsencrypt hasn't released a 0.1.2 version yet.

**Comment by dlapiduz** [comment]
Sorry about this issue, when I upgraded the plugin I didn't realize the version was tied to the upstream client.

Can you try now with version 0.1.3 of the plugin?

**Comment by ChrisRut** [comment]
That fixed it, Thanks
