### ISSUE TITLE
NoCredentialsError only when running as Cronjob

### ISSUE THREAD

**Issue by Rjs37** [dlapiduz/letsencrypt-s3front#22]
I'm at the point of renewal and I noticed the Cronjob I'd setup had failed. 

The output shows a NoCredentialsError. This is the command I'm running under root:

```
/bin/bash /home/forge/bin/cf-letsencrypt.sh
```

When I tried it without `/bin/bash` it failed to find the source, adding that fixed that issue but I'm seeing the credentials error instead. I've tried explicitly stating the credentials as shown in previous examples and also setting the credentials up using `aws configure`.

If I run the .sh script directly from putty then it works (with or without explicitly stating the credentials) without any issues, any ideas?

As the certificate itself is generating okay, I'm probably using up my allotment doing these tests. 

I've included the full error output below in-case it helps
```
2016-02-01 15:25:04,152:ERROR:letsencrypt.error_handler:Encountered exception during recovery
2016-02-01 15:25:04,152:ERROR:letsencrypt.error_handler:Unable to locate credentials
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/letsencrypt/error_handler.py", line 74, in call_registered
    self.funcs[-1]()
  File "build/bdist.linux-x86_64/egg/letsencrypt/auth_handler.py", line 280, in _cleanup_challenges
    self.dv_auth.cleanup(dv_c)
  File "build/bdist.linux-x86_64/egg/letsencrypt_s3front/authenticator.py", line 78, in cleanup
    client.delete_object(Bucket=self.conf('s3-bucket'), Key=achall.chall.path[1:])
  File "/home/forge/.local/share/letsencrypt/local/lib/python2.7/site-packages/botocore-1.3.18-py2.7.egg/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/forge/.local/share/letsencrypt/local/lib/python2.7/site-packages/botocore-1.3.18-py2.7.egg/botocore/client.py", line 396, in _make_api_call
    operation_model, request_dict)
  File "/home/forge/.local/share/letsencrypt/local/lib/python2.7/site-packages/botocore-1.3.18-py2.7.egg/botocore/endpoint.py", line 111, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/forge/.local/share/letsencrypt/local/lib/python2.7/site-packages/botocore-1.3.18-py2.7.egg/botocore/endpoint.py", line 136, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/forge/.local/share/letsencrypt/local/lib/python2.7/site-packages/botocore-1.3.18-py2.7.egg/botocore/endpoint.py", line 120, in create_request
    operation_name=operation_model.name)
  File "/home/forge/.local/share/letsencrypt/local/lib/python2.7/site-packages/botocore-1.3.18-py2.7.egg/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/home/forge/.local/share/letsencrypt/local/lib/python2.7/site-packages/botocore-1.3.18-py2.7.egg/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/home/forge/.local/share/letsencrypt/local/lib/python2.7/site-packages/botocore-1.3.18-py2.7.egg/botocore/signers.py", line 84, in handler
    return self.sign(operation_name, request)
  File "/home/forge/.local/share/letsencrypt/local/lib/python2.7/site-packages/botocore-1.3.18-py2.7.egg/botocore/signers.py", line 119, in sign
    signer.add_auth(request=request)
  File "/home/forge/.local/share/letsencrypt/local/lib/python2.7/site-packages/botocore-1.3.18-py2.7.egg/botocore/auth.py", line 621, in add_auth
    raise NoCredentialsError
NoCredentialsError: Unable to locate credentials
An unexpected error occurred:
NoCredentialsError: Unable to locate credentials
```

**Comment by Rjs37** [comment]
Apologies, found what my issue was. I'd already done a lot of searching before creating this issue but finally found what I problem was. I needed to use the `export` command. 

Either to state the credentials or to explictly state the location of the config file:
```
export AWS_CONFIG_FILE="/home/forge/.aws/config"
```

**Comment by jdiegogonzales** [comment]
I found out that I had to re-install awscli to get rid of this "NoCredentialsError". I had a corrupted, misconfigured or misinstalled version of it that the certbot was reading first instead of the exported variables that I set up even in my bash_profile.
